apiVersion: apps/v1  # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: placement-deployment
spec:
    selector:
        matchLabels:
            app: placement
    replicas: 1
    template:
        metadata:
            labels:
                app: placement
        spec:
            containers:
                - name: placement
                  image: placedock:1.0
# Change this value if you want to use a different database connection
# string for the placement database. Otherwise it will default to a
# sqlite3 database within the container.
#                   env:
#                       - name: DB_STRING
#                         value: "fail badly"
                  ports:
                  - containerPort: 80
