apiVersion: apps/v1  # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: placement-deployment
spec:
  selector:
    matchLabels:
      app: placement
# With the default sqlite database only one replica can be run
# (if you want consistent data). You can change the database
# below to a postgresql database external to the container.
# Or if you add support for client drivers to the container,
# any database you like that is supported by SQLAlchemy.
#  replicas: 1
  template:
    metadata:
      labels:
        app: placement
    spec:
      containers:
      - name: placement
        image: placetest:latest
        imagePullPolicy: Never
# Change this value if you want to use a different database connection
# string for the placement database. Otherwise it will default to a
# sqlite3 database within the container.
        env:
        #- name: OS_PLACEMENT_DATABASE__CONNECTION
        #  value: postgresql+psycopg2://cdent@192.168.1.76/placement?client_encoding=utf8
        - name: OS_DEFAULT__DEBUG
          value: "True"
        - name: OS_PLACEMENT_DATABASE__CONNECTION
          value: sqlite:////cats.db
        - name: DB_SYNC
          value: "True"
        - name: OS_API__AUTH_STRATEGY
          value: noauth2
        ports:
        - containerPort: 80
        # We must set resources for scaling to work.
        resources:
          requests:
            # the docker machine is small, so don't consume too much of it
            cpu: 250m
