version: '3'
services:
  replacedock:
    build: .
    ports:
      - "8081:80"
    environment:
      DB_HOST: neo4j
      OS_API__AUTH_STRATEGY: noauth2
    depends_on:
        - "neo4j"
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    volumes:
        - data:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: none

volumes:
  data:
